// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jhvqvprtlgcvwbgsuuhg.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpodnF2cHJ0bGdjdndiZ3N1dWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxOTgxOTcsImV4cCI6MjA0NTc3NDE5N30.WlihjABBevVCMLekqs2eY7dSZoEUGhLtChNCD0GfiTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);